# Generated by Django 4.2.2 on 2023-06-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_rename_doctor_project_delete_appointment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='special',
            new_name='project',
        ),
    ]
